import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getSponsorBySlug } from "@/lib/services/sponsors.service";
import { TENURE } from "@/lib/config";
import { SponsorClient } from "./SponsorClient";

interface Props {
    params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
    const { slug } = await params;
    const sponsor = await getSponsorBySlug(slug);
    if (!sponsor) return { title: "Sponsor Not Found" };

    const title = `${sponsor.name} × ${TENURE.brandLabel}`;
    const description = sponsor.collectsData
        ? `${sponsor.name} is offering the ${TENURE.brandLabel} family free access to its courses${
              sponsor.tagline ? ` — ${sponsor.tagline.toLowerCase()}` : ""
          }. Sign up to get access.`
        : `${sponsor.name}${sponsor.tagline ? ` — ${sponsor.tagline}` : ""}. Proud sponsor of ${TENURE.brandLabel}.`;

    // The OpenGraph/Twitter image is generated by the colocated opengraph-image.tsx
    // and wired up automatically by Next.
    return {
        title,
        description,
        openGraph: { title, description, type: "website" },
        twitter: { card: "summary_large_image", title, description },
    };
}

export default async function SponsorPage({ params }: Props) {
    const { slug } = await params;
    const sponsor = await getSponsorBySlug(slug);
    if (!sponsor || !sponsor.active) notFound();

    return <SponsorClient sponsor={sponsor} />;
}
